my_string = input('Какие новости на сегодня? ')
print('ну надо же,', my_string.upper(), ',да ладно?')
print(len(my_string))
my_string_1 = input('А еще что интересного? ')
print('во дела,', my_string_1.lower(), ',капец новости конечно...')
print(len(my_string_1))
print(my_string.replace(' ',''))
print(my_string[0])
print(my_string[-1])

